//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vehicles.Core.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali sõiduk nimekirjast.
        /// </summary>
        public static string DefaultSelectPrompt {
            get {
                return ResourceManager.GetString("DefaultSelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahemaa peab olema suurem kui 0..
        /// </summary>
        public static string ErrDistanceInvalid {
            get {
                return ResourceManager.GetString("ErrDistanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark ei tohi olla tühi..
        /// </summary>
        public static string ErrMakeEmpty {
            get {
                return ResourceManager.GetString("ErrMakeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudel ei tohi olla tühi..
        /// </summary>
        public static string ErrModelEmpty {
            get {
                return ResourceManager.GetString("ErrModelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali esmalt sõiduk!.
        /// </summary>
        public static string ErrNoSelection {
            get {
                return ResourceManager.GetString("ErrNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läbisõit ei saa olla negatiivne..
        /// </summary>
        public static string ErrOdoNegative {
            get {
                return ResourceManager.GetString("ErrOdoNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viga.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisesta kehtiv number vahemaa jaoks..
        /// </summary>
        public static string ErrParseDistance {
            get {
                return ResourceManager.GetString("ErrParseDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisatud amfiibauto: {0}.
        /// </summary>
        public static string LogAddedAmphi {
            get {
                return ResourceManager.GetString("LogAddedAmphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisatud paat: {0}.
        /// </summary>
        public static string LogAddedBoat {
            get {
                return ResourceManager.GetString("LogAddedBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisatud auto: {0}.
        /// </summary>
        public static string LogAddedCar {
            get {
                return ResourceManager.GetString("LogAddedCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sõitis maanteel {1} km. Läbisõit: {2} km..
        /// </summary>
        public static string LogAmphiDrive {
            get {
                return ResourceManager.GetString("LogAmphiDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ujus vees {1} km. Läbisõit: {2} km..
        /// </summary>
        public static string LogAmphiSwim {
            get {
                return ResourceManager.GetString("LogAmphiSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ujus {1} km. Läbisõit: {2} km..
        /// </summary>
        public static string LogBoatSwim {
            get {
                return ResourceManager.GetString("LogBoatSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sõitis {1} km. Läbisõit: {2} km..
        /// </summary>
        public static string LogCarDrive {
            get {
                return ResourceManager.GetString("LogCarDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vilgutab tulesid!.
        /// </summary>
        public static string LogFlash {
            get {
                return ResourceManager.GetString("LogFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} annab signaali: Tuut-tuut!.
        /// </summary>
        public static string LogHonk {
            get {
                return ResourceManager.GetString("LogHonk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liikus {1} km. Läbisõit: {2} km..
        /// </summary>
        public static string LogMoveResult {
            get {
                return ResourceManager.GetString("LogMoveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läbisõit: -.
        /// </summary>
        public static string OdometerEmpty {
            get {
                return ResourceManager.GetString("OdometerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läbisõit: {0} km.
        /// </summary>
        public static string OdometerFormat {
            get {
                return ResourceManager.GetString("OdometerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitud: {0} {1}.
        /// </summary>
        public static string SelectedFormat {
            get {
                return ResourceManager.GetString("SelectedFormat", resourceCulture);
            }
        }
    }
}
